# Generated by Django 4.2.30 on 2026-09-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='est_publie',
            field=models.BooleanField(default=False, verbose_name='Publier (Visible par les élèves)'),
        ),
    ]
