# Generated by Django 4.2.30 on 2026-09-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_document_est_publie'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='est_prive',
            field=models.BooleanField(default=True, verbose_name='🔒 Réservé aux abonnés'),
        ),
    ]
