# Generated by Django 4.2.30 on 2026-09-18 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0003_document_est_prive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_premium', models.BooleanField(default=False, verbose_name='Abonnement Premium Actif')),
                ('date_fin_abonnement', models.DateField(blank=True, null=True, verbose_name="Fin d'abonnement")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
